app: ${env:APP}
stage: ${stage} # The debugger only for test env.

component: cynosdb
name: labs_db

inputs:
  region: ${env:REGION}
  zone: ${env:ZONE}
  vpcConfig:
    vpcId: ${output:${stage}:${app}:labs_vpc.vpcId}
    subnetId: ${output:${stage}:${app}:labs_vpc.subnetId}
  dbMode: SERVERLESS
  payMode: 0

# https://github.com/serverless-components/tencent-cynosdb/blob/master/docs/configure.md