app: labs-ktv
stage: prod # The debugger only for test env.

component: vpc
name: labs_vpc


inputs:
  region: ap-guangzhou
  zone: ap-guangzhou-4
  vpcName: labs
  subnetName: labs-serverless

# https://github.com/serverless-components/tencent-vpc/blob/master/docs/configure.md